Import("env")
import os

# Read version from shared ClientVersion.txt (generated by .NET client build)
version_file = os.path.join(env.get("PROJECT_DIR"), "..", "ClientVersion.txt")

if os.path.exists(version_file):
    with open(version_file, "r") as f:
        version = f.read().strip()
else:
    # Fallback if ClientVersion.txt doesn't exist yet
    version = "00000000000000"
    print("WARNING: ClientVersion.txt not found. Build .NET client first to generate version.")

# Generate BuildVersion.h
output_file = os.path.join(env.get("PROJECT_DIR"), "include", "BuildVersion.h")

with open(output_file, "w") as f:
    f.write("#ifndef BUILD_VERSION_H\n")
    f.write("#define BUILD_VERSION_H\n")
    f.write(f'#define BUILD_VERSION "{version}"\n')
    f.write("#endif\n")

print(f"Generated BuildVersion.h with version: {version}")
