[env:pico2w]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico2w
framework = arduino

; Serial monitor configuration
monitor_speed = 115200
upload_protocol = picotool

; LittleFS filesystem configuration
board_build.filesystem_size = 0.5m

build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DPICO_STDIO_USB
    -DPICO_STDIO_UART=0

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2
    bblanchon/ArduinoJson@^7.2.0

; Optional: set upload port
; upload_port = COM5
; or for Linux:
; upload_port = /dev/ttyACM0
