[env:trailer_automation_client_s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

lib_deps = 
    adafruit/Adafruit SHT31 Library@^2.2.2

; Optional: you can set upload_port later in VSCode or here
; upload_port = COM5
; or for Linux:
; upload_port = /dev/ttyACM0
